SET( CPACK_PACKAGE_VERSION_MAJOR ${MAJOR_VERSION} )
SET( CPACK_PACKAGE_VERSION_MINOR ${MINOR_VERSION} )
SET( CPACK_PACKAGE_VERSION_PATCH ${VERSION_FILE_PATCH_VERSION} )
SET( CPACK_PACKAGE_VERSION ${MAJOR_VERSION}.${MINOR_VERSION}.${VERSION_FILE_PATCH_VERSION})
SET( CPACK_PACKAGE_NAME ${APP_NAME} )
SET( CPACK_PACKAGE_INSTALL_DIRECTORY ${APP_NAME} )
SET( CPACK_PACKAGE_VENDOR "${VENDOR} ${EMAIL}" )
SET( CPACK_RESOURCE_FILE_LICENSE ${CMAKE_SOURCE_DIR}/License.txt )
SET( CPACK_PACKAGE_HOMEPAGE_URL ${HOMEPAGE} )
set( CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${VENDOR}/${APP_NAME}" )
SET( CPACK_PACKAGE_DESCRIPTION "Application to help manage your multiple Emby Servers" )
SET( CPACK_PACKAGE_COPYRIGHT ${COPYRIGHT} )

SET(CPACK_NSIS_EXECUTABLES_DIRECTORY "." )
SET(CPACK_PACKAGE_EXECUTABLES 
    "EmbySyncCLI" "EmbySync CLI"
    "EmbySyncGUI" "EmbySync"
)
SET(CPACK_CREATE_DESKTOP_LINKS
    "EmbySyncGUI"
)
    
SET( CPACK_GENERATOR ZIP NSIS )

SET( CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON )
SET( CPACK_NSIS_EXECUTABLES_DIRECTORY "." )

SET( CPACK_NSIS_MODIFY_PATH OFF )

SET( CPACK_NSIS_MUI_ICON ${CMAKE_SOURCE_DIR}/UI/resources/embysync.ico )
SET( CPACK_NSIS_MUI_UNIICON ${CMAKE_SOURCE_DIR}/UI/resources/embysync.ico )

set (CPACK_NSIS_DEFINES 
    "${CPACK_NSIS_DEFINES}
VIProductVersion ${MAJOR_VERSION}.${MINOR_VERSION}.${VERSION_FILE_PATCH_VERSION_HIGH}.${VERSION_FILE_PATCH_VERSION_LOW}
VIFileVersion ${MAJOR_VERSION}.${MINOR_VERSION}.${VERSION_FILE_PATCH_VERSION_HIGH}.${VERSION_FILE_PATCH_VERSION_LOW}
VIAddVersionKey /LANG=0 \\\"ProductName\\\" \\\"${APP_NAME}\\\"
VIAddVersionKey /LANG=0 \\\"ProductVersion\\\" \\\"v${MAJOR_VERSION}.${MINOR_VERSION}.${VERSION_FILE_PATCH_VERSION}\\\"
VIAddVersionKey /LANG=0 \\\"Comments\\\" \\\"${CPACK_PACKAGE_DESCRIPTION}\\\"
VIAddVersionKey /LANG=0 \\\"CompanyName\\\" \\\"${CPACK_PACKAGE_VENDOR}\\\"
VIAddVersionKey /LANG=0 \\\"LegalCopyright\\\" \\\"${CPACK_PACKAGE_COPYRIGHT}\\\"
VIAddVersionKey /LANG=0 \\\"FileDescription\\\" \\\"${APP_NAME} Installer\\\"
VIAddVersionKey /LANG=0 \\\"FileVersion\\\" \\\"v${MAJOR_VERSION}.${MINOR_VERSION}.${VERSION_FILE_PATCH_VERSION}\\\""
)

